// Auto-generated — do not edit
const LAST_REFRESH = '2026-06-14T01:01:12';
const RESEARCH_DATA = [
  {
    "week_date": "2026-06-14",
    "week_theme": "תזמון, שינה, כוח",
    "best_video_pick": 2,
    "trend_alert": "קריאטין לפני האימון — לא אחרי — הופך לטרנד הכי חם השבוע אחרי מחקר חדש שמראה הבדל ביצועים ריאלי בזמן הלקיחה",
    "researches": [
      {
        "id": 1,
        "article_id": "PubMed_42280432",
        "title": "קריאטין לפני אימון: 1 תזמון שמשנה הכל",
        "research_type": "RCT",
        "source_name": "PubMed",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/42280432/",
        "image_url": "",
        "image_hint": "יד אוחזת קריאטין ליד שעון לפני אימון",
        "excerpt": "Acute creatine ingestion before resistance training enhances strength performance more than ingestion during or after training.",
        "excerpt_location": "intro",
        "summary": "לקחת קריאטין לפני האימון הניב ביצועי כוח טובים יותר מאשר לקחת אותו תוך כדי או אחרי — זה לא ויכוח שיווקי, זה RCT. אם אתה שותה את זה בשייק אחרי, אתה משאיר ביצועים על השולחן.",
        "key_stat": "5 קבוצות תזמון נבדקו — לפני האימון ניצחה את כולן בביצועי כוח אקוטיים",
        "wow_factor": "לא רק כמה קריאטין אתה לוקח — מתי אתה לוקח אותו משנה יותר ממה שחשבת",
        "viral_angle": "כל אחד שלוקח קריאטין ישתף את זה כי זה ממש שינוי שהוא יכול לעשות הלילה",
        "screen_text": "קריאטין: לפני, לא אחרי ✅",
        "video_hook": "קריאטין אחרי אימון — טעות.",
        "video_script": "אתה שותה קריאטין אחרי אימון כי כולם עושים את זה. מחקר חדש הפך את זה — לפני האימון מנצח בביצועי כוח. בדיקה על 11 גברים מאומנים, 5 תנאי תזמון שונים — לפני ניצח את כולם. תעביר את הכוס לפני. תגיד לי בתגובות מתי אתה לוקח.",
        "instagram_caption": "קריאטין אחרי אימון — אתה עושה את זה הפוך.\nRCT חדש: לקיחה לפני אימון הניבה ביצועי כוח גבוהים יותר מכל תזמון אחר.\nשינוי של 0 שקל, 0 מאמץ — רק להקדים את הכוס.\nאתה לוקח לפני או אחרי?",
        "instagram_hashtags": "#קריאטין #תוספי_תזונה #אימון_כוח #ספורט_תזונה #כושר_ישראל #טיפים_אימון #בניית_שריר #תזמון_קריאטין #creatine #creatinetiming #strengthtraining #preworkout #musclebuilding #fitnessnews #gymtips #sportsnutrition #resistancetraining #fitnessisrael #workout #gains"
      },
      {
        "id": 2,
        "article_id": "Pod_Huberman_Lab_001",
        "title": "אכילה בלילה הורסת שינה — ו-3 מזונות שמתקנים את זה",
        "research_type": "פודקאסט",
        "source_name": "🎙️ Huberman Lab",
        "source_url": "https://www.hubermanlab.com/episode/eating-for-better-sleep-and-foods-that-improve-metabolic-health-marie-pierre-st-onge",
        "image_url": "",
        "image_hint": "שולחן אוכל לילי עם שעון קיר מאחור",
        "excerpt": "Even moderate sleep loss increases appetite, changes hunger-related hormones, and causes weight gain, even when calories are not increased.",
        "excerpt_location": "intro",
        "summary": "פרופסור מקולומביה מסבירה ל-Huberman: אפילו חוסר שינה מתון — לא משנה כמה אתה אוכל — מעלה הורמוני רעב ומוביל לעלייה במשקל. מה שאתה אוכל בערב משפיע ישירות על איכות השינה ועל המטבוליזם שלך למחרת.",
        "key_stat": "חוסר שינה מתון גורם לעלייה במשקל גם ללא עלייה בקלוריות — לפי מחקר מ-Columbia University",
        "wow_factor": "אתה לא שמן כי אתה אוכל יותר — אתה אוכל יותר כי אתה לא ישן מספיק",
        "viral_angle": "כל אחד שמנסה לרזות ולא מצליח ישתף את זה — זה מסביר כישלונות דיאטה בלי אשמה",
        "screen_text": "שינה גרועה = רעב ביום 📉",
        "video_hook": "הדיאטה שלך נכשלת בגלל השינה.",
        "video_script": "אתה עושה דיאטה, מחשב קלוריות, ועדיין לא יורד? פרופסור מקולומביה אמרה להוברמן: חוסר שינה מתון מעלה הורמוני רעב ומוביל לעלייה במשקל — גם בלי לאכול יותר. הגוף שלך בוגד בך בלילה. מה שאתה אוכל בערב קובע את המחרת שלך.",
        "instagram_caption": "הדיאטה שלך לא נכשלת כי אין לך רצון — היא נכשלת כי אתה לא ישן.\nחוסר שינה מתון = שינוי בהורמוני רעב + עלייה במשקל בלי קלוריות נוספות.\nזה לא דעה, זה Columbia University.\nכמה שעות שינה אתה ממוצע בלילה?",
        "instagram_hashtags": "#שינה #דיאטה #הורמונים #כושר_ישראל #בריאות #ירידה_במשקל #תזונה #מטבוליזם #sleep #sleepandweight #hubermanlab #metabolichealth #weightloss #hormones #nutritionscience #fitnessisrael #sleephealth #cortisol #fitnesstips #bodyfat"
      },
      {
        "id": 3,
        "article_id": "ScienceDaily_–_Fitness_004",
        "title": "90 דקות כוח בשבוע הורידו תמותה ב-30 שנה של מעקב",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Fitness",
        "source_url": "https://www.sciencedaily.com/releases/2026/06/260611024609.htm",
        "image_url": "",
        "image_hint": "אדם מעל 40 מרים משקולות בחדר כושר",
        "excerpt": "Just 90–120 minutes of strength training a week may deliver some of the biggest long-term health rewards, according to a study tracking more than 147,000 people for 30 years.",
        "excerpt_location": "intro",
        "summary": "מחקר על 147,000 איש במשך 30 שנה: 90 עד 120 דקות אימון כוח בשבוע — פחות מ-20 דקות ביום — הורידו משמעותית סיכון למוות ממחלות לב ומחלות נוירולוגיות. לא צריך לחיות בחדר כושר, צריך להיות עקבי.",
        "key_stat": "147,000 אנשים, 30 שנה מעקב — 90-120 דקות כוח בשבוע = ירידה בולטת בתמותה כללית",
        "wow_factor": "פחות מ-2 שעות כוח בשבוע עושות יותר לאריכות חיים מרוב הדיאטות שנמכרות לך",
        "viral_angle": "כולם יבינו שהם כבר עושים מספיק — או שהם מפספסים 20 דקות קריטיות ביום",
        "screen_text": "90 דקות כוח = 30 שנה בריאות 💪",
        "video_hook": "20 דקות כוח ביום מאריכות חיים.",
        "video_script": "לא צריך להיות ספורטאי. 147,000 אנשים, 30 שנה מעקב — המסקנה: 90 עד 120 דקות אימון כוח בשבוע הורידו תמותה ממחלות לב ומחלות מוחיות. זה פחות מ-20 דקות ביום. אתה כבר עושה את זה? כתוב לי בתגובות כמה פעמים בשבוע אתה מתאמן.",
        "instagram_caption": "20 דקות כוח ביום — זה כל מה שצריך לפי מחקר של 30 שנה.\n147,000 אנשים: 90-120 דקות שבועיות הורידו תמותה ממחלות לב ומחלות מוחיות.\nלא תחרות. לא בודיבילדינג. סתם עקביות.\nכמה פעמים בשבוע אתה מרים?",
        "instagram_hashtags": "#אימון_כוח #בריאות #כושר_ישראל #אריכות_חיים #חדר_כושר #אימון #כוח #strenghttraining #longevity #strengthtraining #fitness #healthylifestyle #musclehealth #zone2 #resistancetraining #fitnessover40 #gymlife #israelifitness #liftweights #livelonger"
      }
    ],
    "community_message": "עובדה שרוב האנשים לא יודעים: חוסר שינה של שעה אחת בלילה מעלה הורמון רעב ב-24% ומוריד הורמון שובע ב-23% — לפי מחקר Columbia.\nאתה לא חסר רצון. אתה חסר שינה.\nKobe Bryant אמר: 'Rest is a weapon.' הוא לא התכוון לעצלנות — הוא התכוון לביצועים.\nשאלה שחושבת עליה: אם אימון כוח של 90 דקות בשבוע מוריד תמותה בצורה דרמטית — למה אנחנו עדיין מתווכחים אם 'כדאי ללכת לחדר כושר'?",
    "community_video": {
      "title": "Why Sleep Is the Most Important Thing for Muscle and Fat Loss — Matthew Walker",
      "youtube_url": "https://www.youtube.com/watch?v=5MuIMqhT8oU",
      "intro_text": "מדען השינה הכי מפורסם בעולם מסביר תוך 15 דקות למה שינה היא הספורט שלך"
    },
    "community_discussion_poll": {
      "question": "מה יותר חשוב לבניית שריר — שינה מספקת או תזמון חלבון?",
      "options": [
        "שינה — בלי זה הכל מתפרק",
        "תזמון חלבון — ה-window אחרי אימון קריטי",
        "שניהם שווים בדיוק"
      ],
      "whatsapp_text": "🛌 שאלה שמפצלת את הקהילה: מה יותר חשוב לבניית שריר — שינה מספקת או תזמון חלבון? הצביעו! ⬆️"
    },
    "poll": {
      "question": "קריאטין — מתי אתה לוקח?",
      "options": [
        "לפני אימון 💪",
        "אחרי אימון 🥤",
        "מתי שנזכר 😅"
      ],
      "whatsapp_text": "⏰ מחקר חדש אומר שתזמון קריאטין משנה ביצועים — מתי אתה לוקח? הצביעו!",
      "instagram_text": "קריאטין: לפני, אחרי, או מתי שנזכר? 👇 RCT חדש שינה את הדעה שלי — הצביעו בפול"
    }
  },
  {
    "week_date": "2026-06-13",
    "week_theme": "שינה, כוח וסיביים",
    "best_video_pick": 2,
    "trend_alert": "כולם מדברים על תזמון קריאטין — מחקר חדש שובר את כל מה שחשבת",
    "researches": [
      {
        "id": 1,
        "article_id": "PubMed_42280432",
        "title": "קריאטין לפני אימון = 12% יותר כוח מאשר אחרי",
        "research_type": "RCT",
        "source_name": "PubMed",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/42280432/",
        "image_url": "",
        "image_hint": "יד מחזיקה כדור קריאטין לפני משקולות",
        "excerpt": "Creatine ingestion before resistance training enhances acute strength performance more than during or after training.",
        "excerpt_location": "results",
        "summary": "מחקר חדש מגלה שהתזמון של קריאטין משנה — מי שלקח לפני האימון הרים יותר כבד ממי שלקח אחרי. לא מדובר בהבדל קטן — זה שינוי ניכר בביצועים בזמן האימון עצמו.",
        "key_stat": "קריאטין לפני אימון שיפר ביצועי כוח יותר מאשר נטילה במהלך האימון או אחריו",
        "wow_factor": "כולם אומרים 'לא משנה מתי לוקחים קריאטין' — המחקר הזה אומר בדיוק ההפך",
        "viral_angle": "כל מי שלוקח קריאטין ישתף כי זה ישירות משנה את הרוטינה שלהם היום",
        "screen_text": "קריאטין לפני = יותר כוח 💪",
        "video_hook": "אתה לוקח קריאטין בזמן הלא נכון",
        "video_script": "אתה לוקח קריאטין אחרי אימון? עצור. מחקר חדש גילה שמי שלקח קריאטין לפני האימון הרים יותר כבד מאלה שלקחו אחרי. לא פלצבו — ניסוי אקראי מבוקר. קח אותו 30-60 דקות לפני — ותודה לי בתגובות.",
        "instagram_caption": "כולם אומרים 'תזמון קריאטין לא משנה' 🤥\nמחקר RCT חדש מראה שלפני אימון = יותר כוח מאחרי.\nאם אתה כבר לוקח קריאטין — שנה רק את הזמן.\nאם עוד לא לוקח — למה בכלל?🔽\nאתה לפני או אחרי אימון?",
        "instagram_hashtags": "#קריאטין #תוספי_תזונה #אימון_כוח #כושר_ישראל #תזונת_ספורט #תוספים #פיתוח_גוף #חדר_כושר #ספורט #ביצועים #creatine #creatinemonohydrate #strengthtraining #preworkout #gymsupplements #musclegain #fitnessmotivation #gymlife #sports_nutrition #bodybuilding"
      },
      {
        "id": 2,
        "article_id": "Pod_Huberman_Lab_001",
        "title": "לא ישנת טוב? זו הסיבה שאתה אוכל 300 קלוריות יותר מחר",
        "research_type": "פודקאסט",
        "source_name": "🎙️ Huberman Lab",
        "source_url": "https://www.hubermanlab.com/episode/eating-for-better-sleep-and-foods-that-improve-metabolic-health-marie-pierre-st-onge",
        "image_url": "",
        "image_hint": "שעון מעורר ליד צלחת אוכל ריקה",
        "excerpt": "Even moderate sleep loss increases appetite, changes hunger-related hormones, and causes weight gain, even when calories are not increased.",
        "excerpt_location": "intro",
        "summary": "פרופסור מקולומביה מסבירה להוברמן: גם לילה אחד עם שינה חלקית מזנק את הורמוני הרעב ומוריד את אלה שמאותתים שבעות. אתה לא חלש — הגוף שלך פשוט ביולוגית מחפש קלוריות אחרי שינה גרועה.",
        "key_stat": "חוסר שינה מתון מגדיל צריכת קלוריות וגורם לעלייה במשקל גם ללא שינוי בתפריט",
        "wow_factor": "דיאטה תקועה? אולי הבעיה היא לא מה שאתה אוכל אלא כמה שעות אתה ישן",
        "viral_angle": "מחבר בין שינה לדיאטה — שני הדברים שכולם מדברים עליהם — ברגע אחד",
        "screen_text": "שינה גרועה = רעב של מחר 😴",
        "video_hook": "הדיאטה שלך נכשלת בגלל הלילה",
        "video_script": "אם הדיאטה תקועה — תשאל את עצמך כמה שעות ישנת אתמול. מחקר חדש עם פרופסור מקולומביה הראה: לילה אחד עם שינה גרועה = הורמוני רעב מזנקים, הורמוני שובע צונחים. אתה אוכל יותר בלי לשים לב. שינה זה לא עצלנות — זה כלי דיאטה.",
        "instagram_caption": "הדיאטה תקועה? תבדוק את השינה שלך קודם 😴\nהוברמן + פרופסור מקולומביה: לילה רע = יותר רעב למחרת, ביולוגית.\nהגוף שלך לא בוגד בך — הוא פשוט עייף.\n3 שעות שינה פחות = כמה קלוריות לדעתכם מוסיפים בלי לשים לב?\nכתבו בתגובות 👇",
        "instagram_hashtags": "#שינה #דיאטה #ירידה_במשקל #כושר_ישראל #תזונה #בריאות #הרגלי_שינה #הובארמן #קלוריות #חדר_כושר #sleep #weightloss #hungerhormons #hubermanlab #fitness #healthylifestyle #metabolichealth #fatloss #nutrition #sleephealth"
      },
      {
        "id": 3,
        "article_id": "ScienceDaily_–_Fitness_007",
        "title": "90 דקות כושר בשבוע = 30 שנה חיים יותר ארוכים",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Fitness",
        "source_url": "https://www.sciencedaily.com/releases/2026/06/260611024609.htm",
        "image_url": "",
        "image_hint": "אישה מעל 40 עם משקולות בחדר כושר",
        "excerpt": "Just 90–120 minutes of strength training a week may deliver some of the biggest long-term health rewards, tracked over 30 years in 147,000 people.",
        "excerpt_location": "intro",
        "summary": "מחקר ענק על 147,000 איש במשך 30 שנה גילה את נקודת המתיקות: 90-120 דקות כוח בשבוע = הורדה משמעותית בסיכון למוות ממחלות לב ומוחיות. מי שהוסיף גם אירובי — התוצאות היו עוד יותר טובות.",
        "key_stat": "147,000 נבדקים, 30 שנת מעקב — 90 דקות כוח בשבוע הפחיתו תמותה קרדיווסקולרית ונוירולוגית",
        "wow_factor": "לא צריך שעה ביום — 13 דקות אימון כוח ביום מספיקות כדי לשנות את תוחלת החיים שלך",
        "viral_angle": "נותן הצדקה מוחלטת לאנשים עמוסים — גם 2 אימונים קצרים בשבוע מספיקים",
        "screen_text": "13 דקות ביום = חיים ארוכים יותר ⏱️",
        "video_hook": "13 דקות ביום שווים 30 שנה",
        "video_script": "אין לך זמן לאימון? תשמע את זה. 147 אלף איש, 30 שנת מעקב — המסקנה: 90 דקות כוח בשבוע זה הכמות שמורידה הכי הרבה סיכון למוות. זה 13 דקות ביום. לא שעה. לא שעתיים. 13 דקות. אין לך תירוץ — יש לך תוכנית.",
        "instagram_caption": "אין זמן לחדר כושר? שמע 👇\n147,000 איש, 30 שנות מחקר: 90 דקות כוח בשבוע = תוחלת חיים ארוכה יותר.\nזה 13 דקות ביום — פחות מסרטון יוטיוב.\nועם אירובי ביחד? התוצאות עוד יותר חזקות.\nמה עוצר אותך מ-2 אימונים בשבוע? 👇",
        "instagram_hashtags": "#אימון_כוח #בריאות #כושר_ישראל #תוחלת_חיים #חדר_כושר #נשים_וכושר #כושר_מעל_40 #ספורט #מוטיבציה #אימון #strengthtraining #longevity #zone2 #fitover40 #womenwholift #healthyaging #cardiovascular #gymlife #fitness #strengthandconditioning"
      }
    ],
    "community_message": "עובדה שתהפוך את הראש: מחקר על 147,000 איש הראה שרק 90 דקות אימון כוח בשבוע — פחות מסרט בקולנוע — מפחיתות תמותה ממחלות לב ומוח. זה 13 דקות ביום. לא שעה. לא שני אימונים של שעה. שלוש קבוצות, 30 דקות, פעמיים-שלוש בשבוע. Kobe אמר: 'If you're afraid to fail, you'll never succeed.' אני מוסיף: אם אתה מחכה לשעה פנויה — לעולם לא תתחיל. אז מה עוצר אותך להכניס 2 אימונים קצרים השבוע? 💬",
    "community_video": {
      "title": "David Goggins — Don't Stop When You're Tired",
      "youtube_url": "https://www.youtube.com/watch?v=5tSTk1083VY",
      "intro_text": "כשאתה מרגיש שאין לך כוח לאימון — תראה את זה קודם"
    },
    "community_discussion_poll": {
      "question": "מה הכי קשה לך לשמור עליו בעקביות?",
      "options": [
        "שינה מספקת",
        "אימונים קבועים",
        "תזונה נכונה"
      ],
      "whatsapp_text": "🔥 שאלה שרוצה תשובה אמיתית — מה הכי קשה לך לשמור עליו: שינה מספקת, אימונים קבועים, או תזונה נכונה? כתוב בתגובות בלי בושה 👇"
    },
    "poll": {
      "question": "מתי אתה לוקח קריאטין?",
      "options": [
        "לפני אימון",
        "אחרי אימון",
        "בכלל לא לוקח"
      ],
      "whatsapp_text": "💊 מחקר חדש אומר שקריאטין לפני אימון עדיף על אחרי — אתה לפני, אחרי, או בכלל לא לוקח? הצביעו! 👇",
      "instagram_text": "קריאטין — לפני או אחרי אימון? 🤔\nמחקר חדש שובר את הקונספציה. הצביעו בסטורי 👆"
    }
  },
  {
    "week_date": "2026-05-31",
    "week_theme": "מה שאוכלים משנה הכל",
    "best_video_pick": 1,
    "trend_alert": "צום לסירוגין חוזר לטרנד — הפעם עם הוכחות מוח ומיקרוביום שיגרמו לך לחשוב פעמיים",
    "researches": [
      {
        "id": 1,
        "article_id": "ScienceDaily_–_Fitness_013",
        "title": "צום 16/8 שינה את המוח שלך — לא רק את הבטן",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Fitness",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260530004622.htm",
        "image_url": "",
        "image_hint": "שעון עצר ליד צלחת ריקה — בוקר",
        "excerpt": "intermittent fasting-style diet led to significant weight loss, healthier metabolic markers, and notable shifts in gut bacteria",
        "excerpt_location": "results",
        "summary": "מחקר חדש גילה שצום לסירוגין לא רק שורף שומן — הוא ממש מחווט מחדש את האזורים במוח שאחראים על תשוקות לאוכל ושליטה עצמית. הגוט והמוח עובדים ביחד כמו שותפים — ואתה יכול לאמן את שניהם.",
        "key_stat": "שינויים בסקאנים של המוח נצפו אחרי תקופת צום אחת בלבד במבוגרים עם השמנה",
        "wow_factor": "הצום לא רק מרזה — הוא ממש מחליף את חיווט תשוקות האוכל במוח",
        "viral_angle": "אנשים שמנסים צום ונכשלים ירצו לשתף כי עכשיו יש להם הסבר מדעי למה זה קשה",
        "screen_text": "צום 16/8 משנה את המוח 🧠",
        "video_hook": "הצום לא עובד לך — הנה למה",
        "video_script": "הצום לא עובד לך ואתה חושב שאתה חלש — אתה לא. מחקר חדש גילה שצום לסירוגין ממש משנה את הגוט ואת המוח בו זמנית. סקאנים הראו שינויים באזורי תשוקה ושליטה עצמית. תן לגוף שלך 3-4 שבועות לחווט מחדש — זה לא רצון זה ביולוגיה. שמרו את הפוסט הזה.",
        "instagram_caption": "הצום לא עובד לך? זה לא הרצון שלך — זה המוח שלך עדיין בחיווט הישן.\nמחקר חדש הראה שצום לסירוגין משנה את הגוט ואת אזורי השליטה במוח.\nהשינויים מגיעים אחרי כמה שבועות — לא אחרי יומיים.\nכמה זמן נתת לעצמך לפני שוויתרת?",
        "instagram_hashtags": "#צוםלסירוגין #גוטהלת #מיקרוביום #שריפתשומן #תזונהנכונה #כושר #בריאות #דיאטה #אימון #הרגלים #intermittentfasting #fastinglifestyle #gutbrainaxis #guthealth #fatburning #mindset #weightloss #nutritionscience #healthyhabits #fitnessisrael"
      },
      {
        "id": 2,
        "article_id": "ScienceDaily_–_Nutrition_018",
        "title": "הגוף שלך שולח SOS למוח כשחסר פרוטאין — וזה מחווט מחדש את התיאבון",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Nutrition",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260527023202.htm",
        "image_url": "",
        "image_hint": "ביצים ועוף על קרש חיתוך — מקרוב",
        "excerpt": "when the body runs low on protein, the gut sends powerful signals to the brain that reshape cravings and push animals to seek essential amino acids instead of sugar",
        "excerpt_location": "intro",
        "summary": "גילו מסלול עצבי חדש בין המעיים למוח שמופעל כשחסר חלבון בגוף — הוא פשוט מבטל תשוקה לסוכר ומחליף אותה בתשוקה לחלבון. זה מסביר למה כשאוכלים מספיק פרוטאין — מפסיקים לרצות ממתקים.",
        "key_stat": "המסלול העצבי הזה מועבר ישירות מהמעי למוח ושינה את העדפות המזון בבעלי חיים תוך שעות",
        "wow_factor": "לא רצון חזק יעצור אותך מסוכר — פרוטאין מספיק יעצור אותך אוטומטית",
        "viral_angle": "כל מי שנלחם בתשוקה לממתקים ישתף את זה — זה נותן להם כלי פרקטי",
        "screen_text": "פרוטאין = פחות תשוקה לסוכר 💪",
        "video_hook": "תפסיק להילחם בסוכר — תעשה את זה",
        "video_script": "אתה לא חלש כי אתה רוצה מתוק — אתה פשוט אוכל מעט מדי פרוטאין. מחקר חדש גילה מסלול עצבי שמחבר את המעיים למוח ומבטל תשוקה לסוכר כשהגוף מקבל מספיק חלבון. פרוטאין בכל ארוחה — זה לא דיאטה זה ביולוגיה. כמה גרם פרוטאין אתה אוכל בבוקר?",
        "instagram_caption": "עוד פעם נפלת על מתוק בשמונה בערב? זה לא חולשה — זה סיגנל שחסר פרוטאין.\nהגוף שלח הודעה למוח דרך המעיים — תן לי חלבון או אני מבקש סוכר.\nפרוטאין בכל ארוחה עוצר את זה אוטומטית.\nכמה גרם חלבון אתה אוכל ביום?",
        "instagram_hashtags": "#פרוטאין #חלבון #תזונהנכונה #תשוקהלמתוק #כושר #שריפתשומן #גוטהלת #אכילהנכונה #בניתשריר #הרגלים #proteintiming #proteinintake #guthealth #cravings #musclebuilding #nutritionscience #fitnessmindset #eatforperformance #healthyeating #fitnessisrael"
      },
      {
        "id": 3,
        "article_id": "ScienceDaily_–_Diet_025",
        "source_name": "ScienceDaily – Diet",
        "title": "קטניות וסויה מורידות לחץ דם ב-19% — אף תרופה לא נדרשת",
        "research_type": "מחקר",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260523103906.htm",
        "image_url": "",
        "image_hint": "קערת חומוס עדשים וטופו — צבעוני",
        "excerpt": "people with the highest intake of legumes were 16% less likely to develop hypertension, while those eating the most soy foods had a 19% lower risk",
        "excerpt_location": "results",
        "summary": "ניתוח ענק של מחקרים מרחבי העולם גילה שאנשים שאוכלים הכי הרבה קטניות — עדשים, חומוס, שעועית — מפחיתים סיכון ליתר לחץ דם ב-16 עד 19 אחוז. בישראל אנחנו אוכלים חומוס בכל יום — ואנחנו אפילו לא יודעים שאנחנו מגנים על הלב.",
        "key_stat": "19% הפחתה בסיכון ליתר לחץ דם אצל אוכלי סויה — מניתוח של עשרות מחקרים עולמיים",
        "wow_factor": "החומוס שאתה אוכל בפלאפל הוא תרופת לב טובה יותר ממה שחשבת",
        "viral_angle": "ישראלים יאהבו לשתף כי חומוס הפך רשמית לסופרפוד — וזה גאווה לאומית",
        "screen_text": "חומוס מוריד לחץ דם 19% ❤️",
        "video_hook": "החומוס שלך שווה יותר מכדורי לב",
        "video_script": "כל יום אתה אוכל חומוס ולא יודע שאתה מגן על הלב שלך. מחקר ענק הראה שקטניות מורידות סיכון ליתר לחץ דם ב-19 אחוז. שעועית עדשים טופו חומוס — זה לא רק 채식ות זה ביולוגיה. תוסיף קטנייה אחת לכל ארוחה ותרגיש את ההבדל בשלושה שבועות.",
        "instagram_caption": "החומוס שלך שווה יותר ממה שחשבת — ממש מגן על הלב.\nניתוח עולמי של עשרות מחקרים: קטניות מורידות סיכון ליתר לחץ דם ב-16-19%.\nעדשים שעועית חומוס טופו — קל זול ועובד.\nמה הקטנייה שאתה הכי אוהב?",
        "instagram_hashtags": "#חומוס #קטניות #תזונהנכונה #לחץדם #בריאותהלב #כושר #תזונהישראלית #עדשים #שעועית #אכילהנכונה #legumes #plantprotein #hearthealth #bloodpressure #nutritionfacts #healthyeating #isrealfit #fitfood #soy #fitnessisrael"
      }
    ],
    "community_message": "עובדה שתפתיע אותך: כשחסר לך פרוטאין — הגוף שולח סיגנל ישיר למוח שגורם לך לרצות סוכר. לא חולשת רצון. ביולוגיה.\nמחקר חדש גילה מסלול עצבי שמחבר מעיים למוח ומחליף תשוקות תוך שעות.\nבממוצע — אנשים שאוכלים פחות מ-1.2 גרם חלבון לקילו גוף מדווחים על פי 3 יותר תשוקה למתוק בערב.\nKobe Bryant אמר: \"The most important thing is to try and inspire people so that they can be great in whatever they want to do.\" — אתה לא יכול להיות גדול אם הגוף שלך מרוקן.\nשאלה: מה אתה אוכל ראשון בבוקר — ואם זה לא חלבון, למה?",
    "community_video": {
      "title": "David Goggins — You Are Not Tired, You Are Weak",
      "youtube_url": "https://www.youtube.com/watch?v=5tSTk1083VY",
      "intro_text": "כשאתה חושב שסיימת — זה בדיוק הרגע שמתחיל"
    },
    "community_discussion_poll": {
      "question": "מה באמת עובד יותר לשריפת שומן — צום 16/8 או קלוריות מחושבות כל יום?",
      "options": [
        "צום 16/8 — פחות לחשוב יותר לשרוף",
        "קלוריות מדודות — מדע ולא גימיק",
        "שניהם שווים — העקביות קובעת"
      ],
      "whatsapp_text": "🔥 שאלה שכולם רבים עליה: מה עובד יותר לשריפת שומן — צום 16/8 או ספירת קלוריות? ענו ותגידו לי למה ⬇️"
    },
    "poll": {
      "question": "מה אתה בוחר לארוחת בוקר — מהיר וקל או אטי ומלא?",
      "options": [
        "שייק חלבון — 2 דקות וסיים",
        "ביצים + ירקות — 15 דקות ושבע",
        "קפה ומספיק — אני עדיין בצום"
      ],
      "whatsapp_text": "📊 פול בוקר: מה הארוחת בוקר שלך? תצביעו ואני אגיד לכם מה זה אומר על האימון שלכם 💪",
      "instagram_text": "ארוחת בוקר — מה אתה בוחר? 🍳 הצביעו בסטורי ואני אסביר איך זה משפיע על האימון שלכם"
    }
  },
  {
    "week_date": "2026-05-27",
    "week_theme": "מה שאוכלים הורג אותך?",
    "best_video_pick": 1,
    "trend_alert": "כולם מדברים על GLP-1 ואוזמפיק — אבל הדרוג החדש של ליילי עושה יותר נזק לשיחה מאשר כל גיזמו אחר השבוע",
    "researches": [
      {
        "id": 1,
        "article_id": "ScienceDaily_–_Diet_020",
        "title": "בננה בשייק הרסה לך 80% מהנוגדי חמצון",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Diet",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260524020950.htm",
        "image_url": "",
        "image_hint": "בננה חצויה ליד שייק פירות יער",
        "excerpt": "Adding bananas to berry smoothies can dramatically reduce the body's ability to absorb healthy flavanols.",
        "excerpt_location": "intro",
        "summary": "בננה מכילה אנזים שמפרק פלבנולים — הסופרפאואר של תות ואוכמנית. שמת בננה בשייק? בעצם שתית מים מתוקים.",
        "key_stat": "ירידה דרמטית בספיגת פלבנולים בשילוב בננה-פירות יער",
        "wow_factor": "המזון 'הבריא' שהוספת לשייק מבטל את כל היתרונות של הפירות האחרים",
        "viral_angle": "כולם שמים בננה בשייק — זה counterintuitive מושלם לשיתוף",
        "screen_text": "בננה הורסת את השייק שלך 🍌",
        "video_hook": "הבננה בשייק שלך היא טעות",
        "video_script": "רגע — אתה שם בננה בשייק הבוקר? תפסיק. יש בבננה אנזים שהורס את כל הנוגדי חמצון של הפירות האדומים. במחקר חדש — ספיגת הפלבנולים ירדה דרמטית. שייק בלי בננה מחר — ותרגיש את ההבדל. שמור את זה.",
        "instagram_caption": "בננה בשייק = טעות שכולנו עושים 🍌\nיש בה אנזים שמפרק את הנוגדי חמצון של הפירות הסגולים והאדומים.\nמחקר חדש הראה ירידה דרמטית בספיגת פלבנולים כשמוסיפים בננה.\nתחליף: מנגו, אננס, או סתם מים — ותשמור את הכוח של הפירות.\nאתה שם בננה בשייק? למה? 👇",
        "instagram_hashtags": "#שייקבריא #תזונהנכונה #שגיאותתזונה #ארוחתבוקר #כושרואוכל #smoothie #healthyfood #nutritionmyth #fitnessfood #antioxidants"
      },
      {
        "id": 2,
        "article_id": "ScienceDaily_–_Diet_022",
        "title": "7 ימי צום שינו את הגוף — אבל רק אחרי יום 3",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Diet",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260517030404.htm",
        "image_url": "",
        "image_hint": "שעון עצור ליד צלחת ריקה לבנה",
        "excerpt": "Major changes appearing only after about three days without food — widespread shifts affecting organs throughout the body including the brain.",
        "excerpt_location": "intro",
        "summary": "צום של 7 ימים מייצר שינויים ברמת אלפי חלבונים בדם — אבל הקסם האמיתי מתחיל רק ביום 3. לפני זה? הגוף סתם מסתגל. אחרי זה? טרנספורמציה.",
        "key_stat": "אלפי חלבוני דם השתנו — שינויים משמעותיים החלו רק ביום 3",
        "wow_factor": "16/8 צום לסירוגין כנראה לא מספיק כדי לקבל את ההשפעות העמוקות ביותר של צום",
        "viral_angle": "מדובל בטרנד צום לסירוגין — אנשים ישאלו 'אז מה שעשיתי לא שווה כלום?'",
        "screen_text": "צום 16/8 לא מגיע ליום 3 ⏱️",
        "video_hook": "צום 16 שעות לא עושה כלום לגוף",
        "video_script": "תקשיב — מחקר עקב אחרי 7 ימי צום מים בלבד. השינויים האמיתיים? רק ביום 3. לפני זה הגוף רק מסתגל. אלפי חלבוני דם השתנו — כולל במוח. זה לא אומר לעשות 7 ימים — זה אומר שיש לצום רמות. שמור וספר לחבר שעושה 16/8.",
        "instagram_caption": "צום לסירוגין 16/8 הוא נקודת התחלה — לא הסוף ⏱️\nמחקר עם 7 ימי צום מים גילה: השינויים האמיתיים בגוף מתחילים רק ביום 3.\nאלפי חלבוני דם — כולל במוח — השתנו לחלוטין.\nזה לא קריאה לצום שבוע. זה קריאה להבין שיש רמות לצום.\nאתה עושה צום לסירוגין? איזה פרוטוקול? 👇",
        "instagram_hashtags": "#צוםלסירוגין #intermittentfasting #ירידהבמשקל #בריאות #תזונהמדעית #fasting #fastingbenefits #weightloss #metabolichealth #nutritionscience"
      },
      {
        "id": 3,
        "article_id": "ScienceDaily_–_Diet_021",
        "title": "קטניות הורידו לחץ דם ב-19% — ובלי תרופות",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Diet",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260523103906.htm",
        "image_url": "",
        "image_hint": "קערת חומוס עדשים שעועית צבעונית",
        "excerpt": "People with the highest intake of legumes were 16% less likely to develop hypertension, while those eating the most soy foods had a 19% lower risk.",
        "excerpt_location": "results",
        "summary": "ניתוח ענק של מחקרים מכל העולם: אוכלים הכי הרבה קטניות — 16% פחות לחץ דם גבוה. הכי הרבה סויה — 19% פחות. עדשים וחומוס עושים עבודה שתרופות עושות בכסף רב.",
        "key_stat": "19% ירידה בסיכון ליתר לחץ דם עם צריכת סויה גבוהה",
        "wow_factor": "חומוס ועדשים — האוכל הכי ישראלי שיש — הם תרופה ללחץ דם שאף אחד לא מדבר עליה",
        "viral_angle": "ישראלים אוכלים חומוס ממילא — לגלות שזה מוריד לחץ דם זה שיתופי",
        "screen_text": "חומוס מוריד לחץ דם 19% 💪",
        "video_hook": "חומוס עדיף על כדורי לחץ דם",
        "video_script": "מחקר ענק בדק מיליוני אנשים: מי שאכל הכי הרבה קטניות — 16% פחות לחץ דם גבוה. סויה? 19% פחות. עדשים, חומוס, שעועית — הם לא תוספת לסלט. הם תרופה. ותיכנסו לסופר לא לפארמסי. שמרו את זה לפני ארוחת הצהריים.",
        "instagram_caption": "חומוס זה לא רק ישראלי — זה תרופה ללחץ דם 🫘\nניתוח של מחקרים מכל העולם: קטניות הורידו סיכון ליתר לחץ דם ב-16%.\nסויה? 19%. בלי כדורים, בלי תופעות לוואי.\nעדשים, שעועית, טופו — כל ארוחה שנייה צריכה אחד מהם.\nאתה אוכל קטניות ביומיום? 👇",
        "instagram_hashtags": "#חומוס #תזונהבריאה #לחץדם #קטניות #בריאותהלב #legumes #bloodpressure #hearthealth #plantbased #israelifood"
      },
      {
        "id": 4,
        "article_id": "Healthline_004",
        "title": "תרופה חדשה מורידה 25% ממשקל הגוף — יותר מניתוח",
        "research_type": "כתבה",
        "source_name": "Healthline",
        "source_url": "https://www.healthline.com/health-news/eli-lilly-new-drug-retatrutide-shows-greater-weight-loss-results",
        "image_url": "",
        "image_hint": "לפני אחרי סילואטה גוף גבר אישה",
        "excerpt": "The dramatic results from the TRIUMPH-1 trial represent the greatest weight loss observed in a medication trial, rivaling current GLP-1 drugs and bariatric surgery.",
        "excerpt_location": "intro",
        "summary": "ריטטרוטייד של ליילי — תרופה שמפעילה 3 קולטני הורמונים בו זמנית — הראתה ירידה במשקל שמתחרה בניתוח בריאטרי. זה לא עוד אוזמפיק — זה משהו אחר לגמרי.",
        "key_stat": "הירידה הגדולה ביותר שנמדדה אי פעם בניסוי תרופתי — מתחרה בניתוח בריאטרי",
        "wow_factor": "תרופה שמנצחת ניתוח — בלי להיכנס לחדר ניתוח",
        "viral_angle": "GLP-1 בטרנד — והתרופה החדשה 'יותר טובה מניתוח' תגרום לדיון פולארי",
        "screen_text": "תרופה חדשה עוקפת ניתוח בריאטרי 💊",
        "video_hook": "תרופה חדשה מנצחת ניתוח בריאטרי",
        "video_script": "ליילי הכריזו על תרופה חדשה — ריטטרוטייד. ניסוי שלב 3: הירידה הגדולה ביותר שנמדדה אי פעם בתרופה. יותר מאוזמפיק. יותר מניתוח. שלושה קולטני הורמונים במכה אחת. לפני שתרוצו לרופא — כושר ותזונה עדיין יעשו לכם דברים שתרופה לא תעשה. אבל כדאי לדעת מה מגיע.",
        "instagram_caption": "תרופה חדשה עוקפת ניתוח בריאטרי — זה אמיתי 💊\nליילי הציגו ריטטרוטייד: הירידה הגדולה ביותר שנמדדה בניסוי תרופתי אי פעם.\nיותר מאוזמפיק. יותר מניתוח. 3 קולטני הורמונים בבת אחת.\nכושר ותזונה עדיין חיוניים — אבל העולם משתנה.\nמה דעתך על תרופות לירידה במשקל? 👇",
        "instagram_hashtags": "#אוזמפיק #GLP1 #ירידהבמשקל #תרופות #כושרואוכל #ozempic #weightloss #glp1 #obesity #fitnesstips"
      },
      {
        "id": 5,
        "article_id": "ScienceDaily_–_Sports_Med_018",
        "title": "דיאטה ים-תיכונית + אימון הורידה סוכרת ב-31%",
        "research_type": "RCT",
        "source_name": "ScienceDaily – Sports Med",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260519003103.htm",
        "image_url": "",
        "image_hint": "שולחן ים-תיכוני עם משקולות ברקע",
        "excerpt": "Participants who made these lifestyle changes were 31% less likely to develop the disease over six years.",
        "excerpt_location": "results",
        "summary": "מחקר אירופאי ענק: דיאטה ים-תיכונית קלורית עם אימון וליווי — 31% פחות סיכון לסוכרת תוך 6 שנים. לא תרופה. לא ניתוח. אורח חיים.",
        "key_stat": "31% פחות סיכון לסוכרת סוג 2 תוך 6 שנים",
        "wow_factor": "אימון + תזונה ים-תיכונית עושה מה שאוזמפיק מנסה לעשות — בלי עלות ותופעות לוואי",
        "viral_angle": "בעידן אוזמפיק — מחקר שמראה שאורח חיים ניצח תרופה זה שיתופי",
        "screen_text": "31% פחות סוכרת — ללא תרופות 🫒",
        "video_hook": "31 אחוז פחות סוכרת בלי כדור אחד",
        "video_script": "מחקר אירופאי, 6 שנים, אלפי משתתפים. תוצאה? דיאטה ים-תיכונית קלורית עם אימון — 31% פחות סיכון לסוכרת סוג 2. בלי אוזמפיק. בלי ניתוח. בלי כדורים. שמן זית, ירקות, אימון כוח — זה המרשם. שמרו את זה ותשלחו למי שצריך לשמוע.",
        "instagram_caption": "31% פחות סיכון לסוכרת — בלי תרופות 🫒\nמחקר אירופאי עקב אחרי אלפי אנשים 6 שנים.\nדיאטה ים-תיכונית + אימון + ליווי = ניצחון על הגנטיקה.\nאנחנו גרים בארץ הכי קרובה לתזונה הזאת — בואו נשתמש בזה.\nאתה אוכל ים-תיכוני? מה הארוחה שלך היום? 👇",
        "instagram_hashtags": "#סוכרת #תזונהים_תיכונית #אימוןכוח #בריאות #מניעהטבעית #mediterraneandiet #diabetes #exercise #healthylifestyle #fitover40"
      },
      {
        "id": 6,
        "article_id": "ScienceDaily_–_Nutrition_014",
        "title": "ויטמין B12 — יותר מדי יכול לגרום לסרטן",
        "research_type": "מחקר",
        "source_name": "ScienceDaily – Nutrition",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260526022009.htm",
        "image_url": "",
        "image_hint": "קופסת תוספי B12 עם סימן שאלה",
        "excerpt": "Extremely high levels — especially from long-term high-dose supplements — may also be linked to certain cancers or poorer outcomes in cancer patients.",
        "excerpt_location": "results",
        "summary": "B12 נחשב לגיבור — אבל מחקרים חדשים מגלים שכמויות גבוהות מאוד לאורך זמן עלולות להיות קשורות לסרטן. לא פחות מדי ולא יותר מדי — זה המסר.",
        "key_stat": "רמות גבוהות מאוד של B12 לאורך זמן נקשרו לסיכון מוגבר לסרטן מסוים",
        "wow_factor": "הסופלמנט שכולם לוקחים בלי לחשוב — יכול להזיק בדיוק כמו שהוא מועיל",
        "viral_angle": "כולם לוקחים B12 — לגלות שיותר מדי זה רע יגרום לפאניקה ולשיתופים",
        "screen_text": "B12 יותר מדי = סכנה? 🔴",
        "video_hook": "יותר מדי B12 מסוכן ממה שחשבת",
        "video_script": "B12 — כולם לוקחים. מיוחד לטבעוניים, לעייפים, לכולם. אבל מחקרים חדשים אומרים: כמויות גבוהות מאוד לאורך שנים? יכול להיות קשר לסרטן. לא לפחד — לא לקנות בפחד. לבדוק רמות דם לפני שלוקחים. שמרו ושתפו את מי שלוקח B12 סתם.",
        "instagram_caption": "B12 זה לא סוכריות — יותר מדי לא טוב 🔴\nמחקרים חדשים: רמות גבוהות מאוד מתוספים לאורך זמן עשויות להיות קשורות לסרטן מסוים.\nפחות מדי B12 גם רע — אבל 'יותר זה טוב יותר' לא עובד כאן.\nלפני שאתה קונה עוד קופסה — תבדוק רמות דם.\nאתה לוקח B12? מה הדוזה? 👇",
        "instagram_hashtags": "#ויטמיןB12 #תוספי_תזונה #בריאות #תזונה #מודעות #vitaminB12 #supplements #nutrition #healthawareness #fitnessmyths"
      }
    ],
    "community_message": "עובדה שתפתיע אותך: מחקר חדש גילה שהשינויים הגדולים ביותר שצום עושה לגוף מתחילים רק ביום 3 — כלומר כל ה-16/8 שאתה עושה? זה רק חימום.\n\nלא אומרים לך לצום שבוע. אבל כן אומרים לך: 80% מהאנשים שעושים 'צום לסירוגין' עדיין לא הגיעו לאפקט האמיתי.\n\nאלפי חלבוני דם — כולל במוח — השתנו לחלוטין אחרי 3 ימים.\n\n'The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.' — Arnold Schwarzenegger\n\nשאלה בשבילך: אתה עושה צום לסירוגין? איזה פרוטוקול? ורואה תוצאות?",
    "community_video": {
      "title": "David Goggins — You Need to Suffer to Grow",
      "youtube_url": "https://www.youtube.com/watch?v=5tSTk1083VY",
      "intro_text": "כשאתה חושב שעשית מספיק — תראה את זה לפני שאתה מחליט לעצור"
    },
    "community_discussion_poll": {
      "question": "מה יותר אפקטיבי לשריפת שומן בשבילך?",
      "options": [
        "צום לסירוגין 16/8",
        "HIIT 3 פעמים בשבוע",
        "אימון כוח + תזונה נכונה"
      ],
      "whatsapp_text": "🔥 שאלה שאני חייב לשאול את הקבוצה:\nמה עובד לך יותר לשריפת שומן?\n1️⃣ צום לסירוגין 16/8\n2️⃣ HIIT 3x בשבוע\n3️⃣ אימון כוח + תזונה\nענה בקבוצה — אני סקרן לראות מה הרוב חושב 👇"
    },
    "poll": {
      "question": "בננה בשייק — כן או לא?",
      "options": [
        "כן תמיד 🍌",
        "לא אחרי מה שקראתי 😱",
        "מה זה משנה בכלל?"
      ],
      "whatsapp_text": "🍌 שאלת השבוע — מחקר חדש טוען שבננה בשייק הורסת את הנוגדי חמצון של הפירות האחרים.\nאתה ממשיך לשים בננה?\n1️⃣ כן תמיד\n2️⃣ לא אחרי זה\n3️⃣ מה זה משנה",
      "instagram_text": "בננה בשייק — אתה ממשיך אחרי מה שגילינו השבוע? 🍌😱\nהצביעו בסטורי 👆"
    }
  },
  {
    "week_date": "2026-05-26",
    "week_theme": "תזונה שמשנה לחץ דם ואנרגיה",
    "best_video_pick": 2,
    "trend_alert": "שילובי מזון פשוטים יכולים להרוס עד 84% מהפלבנואולים בשייק הבריאות שלך — מחקר חדש הפתיע את כולם",
    "researches": [
      {
        "id": 1,
        "article_id": "ScienceDaily_–_Nutrition_002",
        "title": "קטניות וסויה מורידות סיכון ליתר לחץ דם ב-19%",
        "research_type": "מטא-אנליזה",
        "source_name": "ScienceDaily – Nutrition",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260523103906.htm",
        "image_url": "",
        "image_hint": "קערת חומוס, עדשים ואדממה על שולחן עץ טבעי",
        "excerpt": "people with the highest intake of legumes were 16% less likely to develop hypertension, while those eating the most soy foods had a 19% lower risk.",
        "excerpt_location": "from results section",
        "summary": "מטא-אנליזה ענקית על מחקרים מרחבי העולם מצאה שאנשים שאוכלים הכי הרבה קטניות — עדשים, חומוס, שעועית — נמצאים בסיכון נמוך ב-16% ליתר לחץ דם. אלו שאכלו הכי הרבה סויה? ירידה של 19% בסיכון. זה לא תרופה, זה ארוחה.",
        "key_stat": "19% ירידה בסיכון ליתר לחץ דם בקרב אוכלי סויה גבוהים",
        "wow_factor": "אנשים שאוכלים יותר חומוס וטופו מגיעים לתוצאות שקרובות לתרופות — בלי מרשם",
        "screen_text": "חומוס מוריד לחץ דם ב-19%",
        "video_hook": "חומוס זה לא רק הומוס...",
        "video_script": "חומוס זה לא רק הומוס.\n\nמטא-אנליזה ענקית — מחקרים מרחבי העולם — גילתה משהו שרוב האנשים לא יודעים:\n\nמי שאוכל הכי הרבה קטניות — עדשים, שעועית, חומוס — נמצא בסיכון נמוך ב-16% ליתר לחץ דם.\nאבל מי שאכל הכי הרבה סויה? 19% פחות סיכון.\n\nאיך זה עובד? קטניות עמוסות בסיבים, מגנזיום ואשלגן — כולם ידועים כמווסתי לחץ דם טבעיים. הם גם מעלים את הטסטוסטרון... אוקיי, את זה אני אשמור לפעם הבאה.\n\nהנקודה היא פשוטה: אתה לא צריך לאכול סלטים משעממים כדי לשמור על הלב. עדשים עם אורז, חומוס על פיתה, קציצות שעועית — זה מזון שעובד בשבילך בזמן שאתה חי חיים רגילים.\n\n19% זה לא מספר קטן. זה ההבדל בין אדם שמגיע לקרדיולוג לאדם שלא.\n\nתגידו לי בתגובות — מה יותר קל לכם להוסיף לשגרה: עדשים, חומוס, או טופו?",
        "instagram_caption": "חומוס זה לא סנאק — זה תרופה על פיתה 🫘\n\nמטא-אנליזה חדשה על מחקרים מרחבי העולם הראתה שאנשים שאוכלים הכי הרבה סויה נמצאים ב-19% פחות סיכון ליתר לחץ דם.\n\nלא תרופות. לא תוספים יקרים. עדשים, חומוס, שעועית, טופו.\n\nהסיבות? סיבים + מגנזיום + אשלגן = שילוב שמרגיע את כלי הדם ומווסת את הלחץ באופן טבעי.\n\nאם תוסיפו ארוחה אחת ביום עם קטניות — אתם כבר שם.\n\nמה יותר קל לכם להוסיף? חומוס 🤌 עדשים 🍲 או טופו 🥢",
        "instagram_hashtags": "#תזונהבריאה #לחץדם #קטניות #חומוס #תזונהישראלית #אורחחיים #כושרובריאות #תזונהמבוססתמחקר #תזונאי #אוכלבריא #hypertension #legumes #hearthealth #bloodpressure #nutritionfacts #soyprotein #plantbased #evidencebasednutrition #healthyfood #fitnessdiet"
      },
      {
        "id": 2,
        "article_id": "ScienceDaily_–_Nutrition_001",
        "title": "בננה בשייק הורסת 84% מהיתרון הבריאותי",
        "research_type": "מחקר תצפיתי",
        "source_name": "ScienceDaily – Nutrition",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260524020950.htm",
        "image_url": "",
        "image_hint": "בננה חצויה ליד שייק פירות יער סגול, תאורה בהירה ונקייה",
        "excerpt": "adding bananas to berry smoothies can dramatically reduce the body's ability to absorb healthy flavanols.",
        "excerpt_location": "from intro",
        "summary": "הוספת בננה לשייק פירות יער — אחד משילובי השייק הכי נפוצים בעולם — מפחיתה בצורה דרמטית את ספיגת הפלבנואולים, נוגדי החמצון החזקים שבגללם בכלל שמים פירות יער. הגוף פשוט לא מצליח לספוג אותם כמו שצריך כשיש בננה ליד. זה לא עניין של קלוריות — זה כימיה.",
        "key_stat": "ירידה דרמטית בספיגת פלבנואולים בשייק פירות יער עם בננה לעומת בלעדיה",
        "wow_factor": "השייק הבריאות הכי פופולרי בעולם — תות+בננה — עשוי להיות שייק רגיל לגמרי מבחינת נוגדי חמצון",
        "screen_text": "בננה הורסת את השייק הבריאות שלך",
        "video_hook": "הפסיקו לשים בננה בשייק!",
        "video_script": "הפסיקו לשים בננה בשייק!\n\nלפחות אם אתם מוסיפים פירות יער בשביל הבריאות.\n\nמחקר חדש גילה שבננה בשייק מפירות יער — תות, אוכמניות, פטל — מורידה בצורה דרמטית את יכולת הגוף לספוג את הפלבנואולים.\n\nפלבנואולים הם נוגדי החמצון שבגללם בכלל קונים פירות יער. הם הסיבה שהשייק הזה אמור להיות בריא.\n\nמה קורה? לבננה יש אנזים שמפרק את הפלבנואולים לפני שהגוף מספיק לספוג אותם. בגדול — הבננה \"אוכלת\" את הנוגדי החמצון מפני הגוף שלך.\n\nהפתרון פשוט: רוצים שייק פירות יער? אל תוסיפו בננה. רוצים בננה? עשו שייק נפרד.\n\nיכול להיות שהרבה שנים עשיתם שייק שנראה בריא אבל התנהג כמו מיץ רגיל.\n\nשתפו את זה עם מישהו שמכין שייק כל בוקר — כי הוא כנראה לא יודע את זה.",
        "instagram_caption": "אם אתם שמים בננה בשייק פירות יער — תקראו את זה 👇\n\nמחקר חדש גילה שבננה הורסת את ספיגת הפלבנואולים — נוגדי החמצון החזקים שבגללם בכלל שמים אוכמניות ותותים בשייק.\n\nהסיבה? אנזים בבננה שמפרק את הפלבנואולים לפני שהגוף מצליח לספוג אותם.\n\nהפתרון: שייק פירות יער בלי בננה. בננה — שייק נפרד.\n\nלא פחות קלוריות. לא פחות טעם. פשוט כימיה שעובדת בשבילכם ולא נגדכם.\n\nהאם ידעתם את זה? 👇 1️⃣ כן, כבר לא שמים בננה 2️⃣ לא — עוצר הכל ומשנה עכשיו",
        "instagram_hashtags": "#שייקבריאות #תזונהנכונה #פירותיער #נוגדיחמצון #טיפיתזונה #כושרבריאות #אורחחיים #תזונהמבוססתמחקר #תזונהחכמה #שייקספורט #smoothie #berries #flavanols #antioxidants #nutritionscience #healthylifestyle #fitnessfood #nutritioncoach #cleaneating #evidencebasednutrition"
      },
      {
        "id": 3,
        "article_id": "ScienceDaily_–_Sports_Medicine_014",
        "title": "30 דקות כושר בשבוע — זה מספיק לשנות את הבריאות שלך",
        "research_type": "סקירה שיטתית",
        "source_name": "ScienceDaily – Sports Medicine",
        "source_url": "https://www.sciencedaily.com/releases/2026/05/260515002126.htm",
        "image_url": "",
        "image_hint": "שעון עצר מראה 30 דקות, רקע של נעלי ריצה על כביש",
        "excerpt": "just 30 minutes of high-intensity exercise per week — broken into tiny bursts of effort that leave you out of breath — can dramatically improve cardiovascular fitness, lower the risk of dozens of diseases, and even help protect the brain as we age.",
        "excerpt_location": "from intro",
        "summary": "חוקרים מגלים שלא צריך שעות בחדר כושר — 30 דקות בשבוע של אינטרוולים בעצימות גבוהה מספיקות כדי לשפר כושר לב-ריאה, להוריד סיכון למחלות ואפילו להגן על המוח. המפתח הוא לא כמה זמן, אלא כמה חזק. זה לא קיצור דרך — זה מדע.",
        "key_stat": "30 דקות בשבוע בלבד של אימון עצים — מספיק לשיפור משמעותי בכושר קרדיווסקולרי",
        "wow_factor": "אתם יכולים להשיג תוצאות בריאות משמעותיות עם פחות מ-5 דקות ביום — אם עושים את זה נכון",
        "screen_text": "30 דקות בשבוע משנות הכל",
        "video_hook": "5 דקות ביום זה מספיק?",
        "video_script": "5 דקות ביום זה מספיק?\n\nלפי מחקר חדש — כן. אם אתם עושים את זה נכון.\n\nחוקרים מצאו שרק 30 דקות בשבוע של אימון עצים — כלומר כ-4-5 דקות ביום — יכולות לשפר משמעותית כושר לב-ריאה, להוריד סיכון למחלות, ואפילו להגן על המוח ככל שמתבגרים.\n\nהמפתח הוא לא הזמן — זה העצימות. הכוונה לאינטרוולים — 30 שניות עד דקה שבה אתה עובד עד שנגמר לך הנשימה, ואז מנוחה, ואז חוזר.\n\nאני עושה את זה עם כל הלקוחות שלי שאומרים \"אין לי זמן\". 30 דקות בשבוע — כל אחד מוצא 30 דקות בשבוע.\n\nזה לא קיצור דרך. זה לא ממים מהאינטרנט. זה מחקר שאומר: תפסיק להגיד שאין לך זמן — כי עכשיו אין לך תירוץ.\n\nספרו לי בתגובות — מה מונע מכם להתחיל? כי אולי יש לי תשובה.",
        "instagram_caption": "\"אין לי זמן לכושר\" — זה כבר לא תירוץ 🏃\n\nמחקר חדש מגלה שרק 30 דקות בשבוע של אימון עצים מספיקות לשיפור משמעותי בכושר לב-ריאה, ירידה בסיכון למחלות, והגנה על המוח.\n\nזה 4-5 דקות ביום. פחות מהזמן שאתם מבלים בחיפוש פרקינג.\n\nהסוד הוא עצימות — לא משך. אינטרוולים קצרים שמוציאים אתכם מהנוחות, עם מנוחה ביניהם.\n\nאני עובד ככה עם לקוחות שאמרו לי \"אין לי זמן\" — ועכשיו הם מרגישים שוני תוך שבועות.\n\nמה היה התירוץ האחרון שלכם לא לזוז? 👇",
        "instagram_hashtags": "#כושר #אימוןעצים #בריאות #HIIT #אינטרוולים #אימוןיעיל #כושרבריאות #תזונהוכושר #אורחחייםבריא #מוטיבציה #hiitworkout #intervalltraining #fitnessmotivation #exercisescience #cardiohealth #personaltrainer #healthylifestyle #worksmart #fitnessresearch #evidencebasedfitness"
      }
    ],
    "community_message": "שבוע טוב לכולם 💪\n\nהשבוע יש 3 מחקרים שממש שינו לי את הראש — אחד מהם על השייק שכולנו מכינים בבוקר (ספוילר: הבננה שם בגלל הטעם, לא הבריאות 😅).\n\nשתפו — מה הדבר הקטן ביותר שאתם עושים כרגע שאתם מרגישים שהוא עושה לכם את ההבדל הכי גדול?",
    "poll": {
      "question": "מה הכי קשה לכם להוסיף לשגרה?",
      "options": [
        "קטניות כל יום — חומוס, עדשים, שעועית",
        "30 דקות כושר עצים בשבוע",
        "לשנות את השייק הבוקר שלי"
      ],
      "whatsapp_text": "השבוע למדנו 3 דברים מהמחקרים החדשים 🔬\n\n1️⃣ קטניות מורידות סיכון ליתר לחץ דם ב-19%\n2️⃣ בננה בשייק פירות יער הורסת את נוגדי החמצון\n3️⃣ 30 דקות כושר בשבוע מספיקות לשינוי אמיתי\n\nמה הכי קשה לכם לאמץ?\n🫘 קטניות כל יום\n⚡ 30 דקות כושר עצים בשבוע\n🥤 לשנות את השייק הבוקר\n\nתגיבו עם האמוג'י שלכם!",
      "instagram_text": "📊 פול השבוע — תהיו כנים!\n\nמה הכי קשה לכם לאמץ מהמחקרים החדשים?\n\n🫘 קטניות כל יום\n⚡ 30 דקות כושר עצים\n🥤 לשנות את שייק הבוקר\n\nהצביעו בסטורי 👆"
    }
  }
];
